alternation

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -145,4 +145,22 @@ jobs:
           echo "Expected exit code 1 for 'dog', got $code2"
           exit 1
          fi
+
+      - name: Run test 12
+        run: |
+         set +e  # Allow commands to fail without exiting
+         echo -n "cat" | python app/main.py -E "(cat|dog)"
+         code1=$?
+         echo -n "dog" | python app/main.py -E "(cat|dog)"
+         code2=$?
+         set -e
+         if [ $code1 -ne 0 ]; then 
+          echo "Expected exit code 0 for 'cat', got $code1"
+          exit 1
+         fi
+
+         if [ $code2 -ne 0 ]; then 
+          echo "Expected exit code 0 for 'dog', got $code2"
+          exit 1
+         fi
     
