end of string anchor

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -59,3 +59,24 @@ jobs:
          fi
 
          echo "Test passed: correct exit codes received"
+
+      - name: Run test 8 
+        run: |
+         set +e  # Allow commands to fail without exiting
+         echo -n "dog" | python app/main.py -E "dog$"
+         code1=$? # $? holds the exit code of the last command that was run
+         echo -n "dogs" | python app/main.py -E "dog$"
+         code2=$?
+         set -e  # Re-enable exit on error
+         if [ $code1 -ne 0 ]; then
+           echo "Expected exit code 0 for 'dog', got $code1"
+           exit 1
+         fi
+
+         if [ $code2 -ne 1 ]; then 
+           echo "Expected exit code 1 for 'dogs', got $code2"
+           exit 1
+         fi
+
+         echo "Test passed: correct exit codes received"
+ 
